import { expect, test } from '@playwright/test'
import { addExpense, open } from './helpers'

test('Plus bütçe: ücretsizde kilitli; önizlemede kategori limiti, uyarı ve tahmin çalışır', async ({ page }) => {
  await open(page, 'butce')
  await expect(page.getByRole('heading', { name: 'Gelişmiş bütçe' })).toBeVisible()
  await page.getByRole('link', { name: 'Paketleri incele' }).click()
  await expect(page.getByRole('heading', { name: 'Paketler', level: 1 })).toBeVisible()
  await expect(page.getByText('Kullandığınız paket')).toBeVisible()

  await page.getByRole('radiogroup', { name: 'Önizleme paketi' }).getByRole('radio', { name: 'Plus', exact: true }).click()
  await page.getByRole('link', { name: 'Aç' }).first().click()
  await expect(page.getByRole('heading', { name: 'Bütçe planı' })).toBeVisible()
  await expect(page.getByText('Henüz kategori limiti yok')).toBeVisible()

  await page.getByRole('button', { name: 'Limit ekle' }).click()
  const dlg = page.getByRole('dialog', { name: 'Kategori limiti ekle' })
  await dlg.getByLabel('Kategori').selectOption({ label: 'Market' })
  await dlg.getByLabel('Tutar (TL)').fill('100')
  await dlg.getByRole('button', { name: 'Kaydet' }).click()
  await expect(dlg).toBeHidden()
  await expect(page.getByRole('progressbar', { name: 'Market limit kullanımı' })).toBeVisible()

  await addExpense(page, { amount: '90', description: 'Bakkal', category: 'Market' })
  const warn = page.getByRole('region', { name: 'Bütçe uyarıları' })
  await expect(warn).toContainText('Market')
  await expect(warn).toContainText('%90 kullanıldı')
  await expect(page.getByText(/Dönemin \d+ gününün \d+\. günündesiniz/)).toBeVisible()

  // Panelde uyarı sayısı görünür
  await page.goto('./#/')
  await expect(page.getByRole('link', { name: /Bütçe planı.*1 uyarı/ })).toBeVisible()
})

test('Plus düzenli ödemeler: abonelik eklenir, yaklaşan ödeme ve panel hatırlatması görünür', async ({ page }) => {
  await open(page, 'paketler')
  await page.getByRole('radiogroup', { name: 'Önizleme paketi' }).getByRole('radio', { name: 'Plus', exact: true }).click()
  await page.goto('./#/odemeler')
  await expect(page.getByRole('heading', { name: 'Düzenli ödemeler', level: 1 })).toBeVisible()
  await expect(page.getByText('Henüz düzenli ödeme yok')).toBeVisible()

  const tomorrow = await page.evaluate(() => {
    const d = new Date(Date.now() + 86_400_000)
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
  })
  await page.getByRole('button', { name: 'Ekle', exact: true }).click()
  const dlg = page.getByRole('dialog', { name: 'Düzenli ödeme ekle' })
  await dlg.getByLabel('Ad').fill('Dijital yayın')
  await dlg.getByLabel('Tutar (TL)').fill('229,99')
  await dlg.getByLabel('İlk ödeme tarihi').fill(tomorrow)
  await dlg.getByRole('button', { name: 'Kaydet' }).click()
  await expect(dlg).toBeHidden()

  const upcoming = page.getByRole('list', { name: 'Yaklaşan ödemeler' })
  await expect(upcoming).toContainText('Dijital yayın')
  await expect(upcoming).toContainText('Yarın')
  await expect(upcoming).toContainText('Yaklaştı')
  await expect(page.getByRole('table')).toContainText('229,99')

  // Elle taksit
  await page.getByRole('button', { name: 'Taksit ekle' }).click()
  const inst = page.getByRole('dialog', { name: 'Taksit ekle' })
  await inst.getByLabel('Ad').fill('Telefon')
  await inst.getByLabel('Aylık taksit tutarı (TL)').fill('1.000')
  await inst.getByLabel('İlk taksit tarihi').fill(tomorrow)
  await inst.getByRole('button', { name: 'Kaydet' }).click()
  await expect(inst).toBeHidden()
  await expect(page.getByText(/Aylık · sıradaki .* · 0\/6 ödendi/)).toBeVisible()

  await page.goto('./#/')
  await expect(page.getByRole('link', { name: 'Yaklaşan ödemeler' })).toContainText('Dijital yayın')
})

test('Plus birikim hedefi ve raporlar: hedef eklenir, para eklenip çekilir; rapor dönemi özetler', async ({ page }) => {
  await open(page, 'hedefler')
  await expect(page.getByRole('heading', { name: 'Birikim hedefleri', level: 2 })).toBeVisible()
  await page.goto('./#/paketler')
  await page.getByRole('radiogroup', { name: 'Önizleme paketi' }).getByRole('radio', { name: 'Plus', exact: true }).click()
  await page.goto('./#/hedefler')
  await expect(page.getByText('Henüz birikim hedefi yok')).toBeVisible()
  await page.getByRole('button', { name: 'Tatil' }).click()
  const dlg = page.getByRole('dialog', { name: 'Birikim hedefi ekle' })
  await expect(dlg.getByLabel('Hedefin adı')).toHaveValue('Tatil')
  await dlg.getByLabel('Hedef tutar (TL)').fill('10.000')
  await dlg.getByRole('button', { name: 'Kaydet' }).click()
  await expect(dlg).toBeHidden()

  const card = page.getByRole('article', { name: 'Tatil' })
  await expect(card).toContainText('Tarihsiz')
  await card.getByRole('button', { name: 'Para ekle' }).click()
  const add = page.getByRole('dialog', { name: 'Hedefe para ekle' })
  await add.getByLabel('Tutar (TL)').fill('2.500')
  await add.getByRole('button', { name: 'Kaydet' }).click()
  await expect(add).toBeHidden()
  await expect(card.getByRole('progressbar', { name: 'Tatil ilerlemesi' })).toHaveAttribute('aria-valuenow', '25')

  await card.getByRole('button', { name: 'Çek' }).click()
  const take = page.getByRole('dialog', { name: 'Hedeften para çek' })
  await take.getByLabel('Tutar (TL)').fill('5.000')
  await take.getByRole('button', { name: 'Kaydet' }).click()
  await expect(take.getByText('Biriktirdiğinizden fazlasını çekemezsiniz.')).toBeVisible()
  await take.getByLabel('Tutar (TL)').fill('500')
  await take.getByRole('button', { name: 'Kaydet' }).click()
  await expect(take).toBeHidden()
  await expect(card).toContainText('2.000,00 ₺')

  await addExpense(page, { amount: '450', description: 'Kırtasiye', category: 'Market' })
  await page.goto('./#/raporlar')
  await expect(page.getByRole('heading', { name: 'Raporlar', level: 1 })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Dönem özeti' })).toContainText('450,00 ₺')
  await expect(page.getByRole('table', { name: 'Kategori karşılaştırması' })).toContainText('Market')
  await expect(page.getByRole('list', { name: 'İş yerleri' })).toContainText('Kırtasiye')
  await expect(page.getByText('Karşılaştırma için önceki dönemlerden kayıt gerekiyor.', { exact: false })).toBeVisible()
})

test('Plus varlıklarım: altın eklenir, fiyat güncellenir, satılır, borç net varlıktan düşer', async ({ page }) => {
  await open(page, 'paketler')
  await page.getByRole('radiogroup', { name: 'Önizleme paketi' }).getByRole('radio', { name: 'Plus', exact: true }).click()
  await page.goto('./#/varliklar')
  await expect(page.getByText('Henüz varlık eklenmedi')).toBeVisible()

  await page.getByRole('button', { name: 'Altın', exact: true }).click()
  let dlg = page.getByRole('dialog', { name: 'Varlık ekle' })
  await dlg.getByRole('button', { name: 'Gram altın' }).click()
  await dlg.getByLabel('Miktar (gram)').fill('10')
  await dlg.getByLabel('Birim alış fiyatı (TL)').fill('4.000')
  await dlg.getByLabel('Alış tarihi').fill('2026-09-01')
  await dlg.getByRole('button', { name: 'Kaydet' }).click()
  await expect(dlg).toBeHidden()

  const list = page.getByRole('list', { name: 'Varlıklar' })
  await expect(list).toContainText('Gram altın')
  await expect(list).toContainText('40.000,00 ₺')

  await list.getByRole('button', { name: /Fiyatı güncelle/ }).click()
  const pr = page.getByRole('dialog', { name: 'Fiyatı güncelle' })
  await pr.getByLabel('Güncel birim fiyat (TL / gram)').fill('4.500')
  await pr.getByRole('button', { name: 'Kaydet' }).click()
  await expect(pr).toBeHidden()
  await expect(list).toContainText('45.000,00 ₺')
  await expect(list).toContainText('+5.000,00 ₺')
  await expect(list).toContainText('Fiyat elle girildi')

  await list.getByRole('button', { name: /Alış \/ satış/ }).click()
  const tr = page.getByRole('dialog', { name: 'Alış veya satış ekle' })
  await tr.getByRole('radio', { name: 'Satış' }).click()
  await tr.getByLabel('Miktar (gram)').fill('20')
  await tr.getByLabel('Birim fiyat (TL)').fill('4.500')
  await tr.getByRole('button', { name: 'Kaydet' }).click()
  await expect(tr.getByText('Elinizdekinden fazlasını satamazsınız.')).toBeVisible()
  await tr.getByLabel('Miktar (gram)').fill('2')
  await tr.getByRole('button', { name: 'Kaydet' }).click()
  await expect(tr).toBeHidden()

  await page.getByRole('button', { name: 'Borç ekle' }).click()
  dlg = page.getByRole('dialog', { name: 'Borç ekle' })
  await dlg.getByRole('button', { name: 'Kredi kartı borcu' }).click()
  await dlg.getByLabel('Kalan borç (TL)').fill('6.000')
  await dlg.getByRole('button', { name: 'Kaydet' }).click()
  await expect(dlg).toBeHidden()

  const sum = page.getByRole('region', { name: 'Net varlık' })
  // 8 gram × 4.500 = 36.000; − 6.000 borç
  await expect(sum).toContainText('30.000,00 ₺')
  await expect(sum).toContainText('Gerçekleşen +1.000,00 ₺')
  await expect(page.getByRole('list', { name: 'Varlık dağılımı' })).toContainText('Altın')
  await expect(page.getByRole('table')).toContainText('36.000,00 ₺')
})

test('Plus+ yolculuk, senaryolar ve bilgi: anket doğrulanır, aşamalar ve göstergeler hesaplanır', async ({ page }) => {
  await open(page, 'paketler')
  await page.getByRole('radiogroup', { name: 'Önizleme paketi' }).getByRole('radio', { name: 'Plus+', exact: true }).click()
  await page.goto('./#/varliklar')
  await page.getByRole('button', { name: 'Altın', exact: true }).click()
  const dlg = page.getByRole('dialog', { name: 'Varlık ekle' })
  await dlg.getByRole('button', { name: 'Gram altın' }).click()
  await dlg.getByLabel('Miktar (gram)').fill('10')
  await dlg.getByLabel('Birim alış fiyatı (TL)').fill('4.000')
  await dlg.getByRole('button', { name: 'Kaydet' }).click()
  await expect(dlg).toBeHidden()

  // Senaryolar ankete bağlıdır
  await page.goto('./#/senaryolar')
  await expect(page.getByRole('heading', { name: 'Önce yolculuğunuzu oluşturun' })).toBeVisible()

  await page.goto('./#/yolculuk')
  const survey = page.getByRole('region', { name: 'Yolculuk anketi' })
  await expect(survey).toContainText('Eksik')
  await expect(survey).toContainText('40.000,00 ₺')
  await survey.getByRole('button', { name: 'Doğruladım, rotamı oluştur' }).click()
  await expect(survey.getByRole('alert')).toContainText('Hedefte aylık yaşam gideri için geçerli bir tutar girin.')
  await survey.getByLabel(/Hedefte aylık yaşam gideri/).fill('25.000')
  await survey.getByLabel(/Aylık net gelir/).fill('50.000')
  await survey.getByLabel(/Zorunlu aylık giderler/).fill('20.000')
  await survey.getByRole('button', { name: 'Doğruladım, rotamı oluştur' }).click()

  // 40.000 / 20.000 = 2 ay; hedef 25.000 × 12 / %4 = 7.500.000
  await expect(page.getByRole('region', { name: 'Finansal güvence' })).toContainText('2 ay')
  await expect(page.getByRole('region', { name: 'Hedef ilerlemesi' })).toContainText('7.500.000,00 ₺')
  await expect(page.getByRole('region', { name: 'Tahmini rota' })).toContainText('Ayda 30.000,00 ₺ birikimle')
  const stages = page.getByRole('list', { name: 'Aşamalar' })
  await expect(stages.getByRole('listitem').filter({ hasText: 'Bütçe dengesi' })).toContainText('Tamamlandı')
  await expect(stages.getByRole('listitem').filter({ hasText: 'Acil durum birikimi' })).toContainText('20.000 ₺ daha biriktirin')
  await expect(stages.getByRole('listitem').filter({ hasText: 'Düzenli birikim' })).toContainText('Tamamlandı')
  await expect(page.getByText(/Kilometre taşı:/)).toBeVisible()

  // Bilgileri düzenleme anketi doldurulmuş açar
  await page.getByRole('button', { name: 'Bilgilerimi düzenle' }).click()
  await expect(page.getByLabel(/Aylık net gelir/)).toHaveValue('50.000,00')
  await page.getByRole('button', { name: 'Vazgeç' }).click()

  await page.getByRole('link', { name: 'Senaryolar' }).first().click()
  await expect(page).toHaveURL(/#\/senaryolar/)
  const table = page.getByRole('region', { name: 'Senaryo tablosu' })
  await expect(table).toContainText('40.000,00 ₺')
  await expect(page.getByRole('list', { name: 'Hedefe ulaşma' })).toContainText('Temkinli')
  // Gelir kaybı ilk yılda birikimi azaltır
  const before = await table.getByRole('row').nth(2).textContent()
  await page.getByLabel('Gelir kaybı (ay)').fill('6')
  await expect(table.getByRole('row').nth(2)).not.toHaveText(before ?? '')
  await page.getByRole('radio', { name: 'Nominal' }).click()
  await expect(table).toContainText('(nominal)')
  await expect(page.getByText('olasılık veya garanti değildir')).toBeVisible()

  await page.goto('./#/ogren')
  await expect(page.getByText('Likidite', { exact: true })).toBeVisible()
  await expect(page.getByText(/Henüz yayınlanmış rapor yok/)).toBeVisible()
})

test('Plus+ koç: borç önce kapanır, yatırım tutarı ve yapılandırma hesabı; hazır sorular yanıtlanır', async ({ page }) => {
  await open(page, 'paketler')
  await page.getByRole('radiogroup', { name: 'Önizleme paketi' }).getByRole('radio', { name: 'Plus+', exact: true }).click()
  await page.goto('./#/koc')
  await expect(page.getByRole('region', { name: 'Koç özeti' })).toContainText('Sizi tanıyınca')
  await expect(page.getByRole('region', { name: 'Koç mesajları' })).toContainText('Sizi tanıyalım')

  await page.goto('./#/varliklar')
  await page.getByRole('button', { name: 'Borç ekle' }).click()
  const dlg = page.getByRole('dialog', { name: 'Borç ekle' })
  await dlg.getByRole('button', { name: 'Kredi kartı borcu' }).click()
  await dlg.getByLabel('Kalan borç (TL)').fill('30.000')
  await dlg.getByLabel('Aylık faiz (%)').fill('4,25')
  await dlg.getByLabel('Aylık ödeme (TL)').fill('3.000')
  await dlg.getByRole('button', { name: 'Kaydet' }).click()
  await expect(dlg).toBeHidden()
  await expect(page.getByRole('list', { name: 'Borçlar' })).toContainText('Aylık %4,25 faiz · aylık ödeme 3.000,00 ₺')

  await page.goto('./#/yolculuk')
  await page.getByLabel(/Hedefte aylık yaşam gideri/).fill('25.000')
  await page.getByLabel(/Aylık net gelir/).fill('50.000')
  await page.getByLabel(/Zorunlu aylık giderler/).fill('40.000')
  await page.getByRole('button', { name: 'Doğruladım, rotamı oluştur' }).click()
  await expect(page.getByRole('region', { name: 'Finansal güvence' })).toBeVisible()

  await page.goto('./#/koc')
  // Fazla 10.000; düzenli gelirde %90'ı (9.000) plana ayrılır
  const plan = page.getByRole('region', { name: 'Planın' })
  await expect(plan.getByRole('listitem').first()).toContainText('Borçları kapat')
  await expect(plan).toContainText('Ayda 9.000,00 ₺')
  await expect(plan).toContainText('Düzenli yatırım')
  const debt = page.getByRole('region', { name: 'Borç planı' })
  await expect(debt).toContainText('4 ay')
  await expect(debt).toContainText('Yalnızca asgari ödemeye göre')

  const chat = page.getByRole('region', { name: 'Koç mesajları' })
  await expect(chat).toContainText('Bu ayın planı')
  await chat.getByRole('button', { name: 'Her ay ne kadar yatırıma ayırmalıyım?' }).click()
  await expect(chat).toContainText('Ayda 9.000 ₺ ayırabilirsiniz')
  await expect(chat.getByLabel('Koça yazın')).toBeDisabled()

  await debt.getByRole('button', { name: 'Yapılandırma hesabı' }).click()
  await debt.getByLabel('Yeni aylık faiz (%)').fill('1,5')
  await debt.getByLabel('Vade (ay)').fill('12')
  await expect(debt.getByLabel('Yapılandırma sonucu')).toContainText('Faiz tasarrufu')

  await debt.getByRole('radio', { name: 'Önce en küçük borç' }).click()
  await page.goto('./#/')
  await expect(page.getByRole('link', { name: 'Koç mesajları' })).toBeVisible()
  await page.goto('./#/koc')
  await expect(page.getByRole('radio', { name: 'Önce en küçük borç' })).toHaveAttribute('aria-checked', 'true')
})
